apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: nodejs-intive-app28-pipeline-run-init
  namespace: demo-dev
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded  
  labels:
    tekton.dev/pipeline: nodejs-intive-app28-pipeline
    janus-idp.io/tekton: nodejs-intive-app28
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https://github.com/intive-RedHat-Devex-demo/nodejs-intive-app28.git'
    - name: source-branch
      value: main
    - name: output-image
      value: image-registry.openshift-image-registry.svc:5000/nodejs-intive-app28/nodejs-intive-app28
  pipelineRef:
    name: nodejs-intive-app28-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
